print('✅ SCRAPER LOGOLÁS MÓDOSÍTVA')
print('============================')
print()
print('📝 VÁLTOZÁSOK:')
print('• Emelet/szint logolás eltávolítva a részletes scraperből')
print('• Szobaszám logolás hozzáadva minden ingatlan feldolgozásánál')
print('• Format: "🏠 Szobák: [érték]" vagy "🏠 Szobák: nincs adat"')
print()
print('🔍 MIT LÁTSZ FUTÁS KÖZBEN:')
print('  🏠 1/10: https://ingatlan.com/34931913')
print('    🎯 Állapot: jó állapotú') 
print('    🏠 Szobák: 10              <- ÚJ!')
print('    ✅ Kinyert mezők: 7/31')
print('    ⏰ Várakozás 1.8s...')
print()
print('📊 ELŐNY:')
print('• Azonnal látod, hogy a scraper megtalálja-e a szobaszámot')
print('• Egyszerűbb debug a szobaszám kinyerés ellenőrzéséhez')
print('• Kevésbé fontos emelet info eltávolítva a tisztább logért')
